# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        script: |
            mkdir -p ~/my-express-app/ # create a new folder
            cd ~/my-express-app/ # navigate into the folder
            git clone https://github.com/kamleshkatpara/express-github-actions app # clone the repo into the 'app' folder
            cd express-github-actions # navigate into the repo
            npm install # install dependencies 
            npm start # start as a background service.